# Generated by Django 5.2.7 on 2025-11-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('AFEGANISTÃO', 'Afghanistan'), ('ALEMANHA', 'Germany'), ('ARGENTINA', 'Argentina'), ('AUSTRÁLIA', 'Australia'), ('ÁUSTRIA', 'Austria'), ('BÉLGICA', 'Belgium'), ('BOLÍVIA', 'Bolivia'), ('BRASIL', 'Brazil'), ('CANADÁ', 'Canada'), ('CHILE', 'Chile'), ('CHINA', 'China'), ('COLÔMBIA', 'Colombia'), ('COREIA DO SUL', 'South Korea'), ('CUBA', 'Cuba'), ('DINAMARCA', 'Denmark'), ('EGITO', 'Egypt'), ('EMIRADOS ÁRABES UNIDOS', 'United Arab Emirates'), ('ESPANHA', 'Spain'), ('ESTADOS UNIDOS', 'United States'), ('FILIPINAS', 'Philippines'), ('FINLÂNDIA', 'Finland'), ('FRANÇA', 'France'), ('GRÉCIA', 'Greece'), ('HOLANDA', 'Netherlands'), ('HONG KONG', 'Hong Kong'), ('HUNGRIA', 'Hungary'), ('ÍNDIA', 'India'), ('INDONÉSIA', 'Indonesia'), ('INGLATERRA', 'England'), ('IRÃ', 'Iran'), ('IRAQUE', 'Iraq'), ('IRLANDA', 'Ireland'), ('ISLÂNDIA', 'Iceland'), ('ISRAEL', 'Israel'), ('ITÁLIA', 'Italy'), ('JAPÃO', 'Japan'), ('LÍBANO', 'Lebanon'), ('MÉXICO', 'Mexico'), ('MARROCOS', 'Morocco'), ('NIGÉRIA', 'Nigeria'), ('NORUEGA', 'Norway'), ('NOVA ZELÂNDIA', 'New Zealand'), ('PAQUISTÃO', 'Pakistan'), ('PERU', 'Peru'), ('POLÔNIA', 'Poland'), ('PORTUGAL', 'Portugal'), ('REINO UNIDO', 'United Kingdom'), ('REPÚBLICA TCHECA', 'Czech Republic'), ('RÚSSIA', 'Russia'), ('SUÉCIA', 'Sweden'), ('TAILÂNDIA', 'Thailand'), ('TURQUIA', 'Turkey')], max_length=100, null=True),
        ),
    ]
